### ISSUE TITLE
不如直接fork仓库只留framework分支

### ISSUE THREAD

**Issue by 985892345** [hiyasame/AmeProjectTemplate-Android#1]
好家伙，直接拿来用了是吧😏

**Comment by hiyasame** [comment]
😏之后想往lib_common里面加点私货

**Comment by hiyasame** [comment]
其实之前我就在想能不能把lib_common打包供其他项目调用 但又想到gradle配置这种东西没办法打包 不如直接维护一个项目模板

**Comment by 985892345** [comment]
lib_common不建议添加其他东西，应该保证绝对的基础，而不是当成工具模块使用，工具模块可以额外新建

**Comment by 985892345** [comment]
> 其实之前我就在想能不能把lib_common打包供其他项目调用 但又想到gradle配置这种东西没办法打包 不如直接维护一个项目模板

不会啊，你直接打包成aar包就可以了，aar包只会有源码，与gradle没有关系，使用jitpack发布就行，jitpack在我课上有使用讲解

**Comment by 985892345** [comment]
> > 其实之前我就在想能不能把lib_common打包供其他项目调用 但又想到gradle配置这种东西没办法打包 不如直接维护一个项目模板
> 
> 不会啊，你直接打包成aar包就可以了，aar包只会有源码，与gradle没有关系，使用jitpack发布就行，jitpack在我课上有使用讲解

直接新建一个项目，正常建一个模块，然后按我给的教程添加maven-publish插件，发布就可以了

**Comment by 985892345** [comment]
想要gradle配置可以直接把build_logic当成gradle插件发布，所以整个项目都可以供其他项目直接使用的

**Comment by hiyasame** [comment]
确实哈
